# Generated by Django 5.1.4 on 2025-01-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institution",
            old_name="domain",
            new_name="domain_url",
        ),
        migrations.AddField(
            model_name="institution",
            name="schema_name",
            field=models.CharField(
                default="default_schema", max_length=255, unique=True
            ),
        ),
    ]
