# Generated by Django 5.1.4 on 2025-01-05 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_domain_institution_domain_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Institution",
        ),
    ]
